version: 1.0.{build}

configuration: Release

os: Visual Studio 2015

install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build: 
  verbosity: minimal

before_build:
  - nuget restore