version: 1.0.{build}

image: Visual Studio 2017

install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  - nuget restore

build_script:
  - msbuild "ReferencePathManager.sln" /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
